Fix zcap expiration
digitalbazaar/bedrock-profile-http pull request #24
Opened 2020-09-17 20:53 UTC by JSAssassin

fix related to this issue https://github.com/digitalbazaar/bedrock-profile-http/issues/16

2020-09-17 21:14 UTC, dlongley requested changes

2020-09-17 21:14 UTC, dlongley commented on lib/http.js
> +      const {invoker, account, expires} = req.body;
I don't think we want to allow `expires` to be set by the client. It's an attack vector, let's remove that and always set it to the configured value.

2020-09-25 17:55 UTC, mattcollier approved these changes

2020-09-25 18:20 UTC, dlongley approved these changes

2020-09-25 18:37 UTC, merged